# Generated by Django 2.1.7 on 2019-04-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20190410_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phones',
        ),
    ]
