# Generated by Django 2.1.7 on 2019-04-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='weathers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wCity', models.CharField(max_length=16)),
                ('wDate', models.DateField()),
                ('wWeather', models.CharField(max_length=64)),
                ('wTeap', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='test',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
    ]
