# Generated by Django 2.1.7 on 2019-04-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20190410_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathers',
            name='wCity',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='weathers',
            name='wDate',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='weathers',
            name='wTeap',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='weathers',
            name='wWeather',
            field=models.CharField(default='', max_length=64),
        ),
    ]
