# Generated by Django 2.1.7 on 2019-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_delete_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wMark', models.CharField(max_length=256)),
                ('wNote', models.CharField(max_length=1024)),
                ('wPrice', models.CharField(max_length=32)),
            ],
        ),
    ]
