# Generated by Django 2.1.7 on 2019-06-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0010_auto_20190611_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meiju',
            new_name='movie',
        ),
    ]
